export enum ApiError {
  FETCH_DATASETS = "Failed to fetch datasets",
  FETCH_COLLECTIONS = "Failed to fetch collections",
  FETCH_USER_COLLECTIONS = "Failed to fetch user collections",
  CREATE_COLLECTION = "Failed to create collection",
  ADD_DATASET_TO_COLLECTION = "Failed to add dataset to collection",
  REMOVE_DATASET_FROM_COLLECTION = "Failed to remove dataset from collection",
  DELETE_COLLECTION = "Failed to delete collection",
  SEARCH_IN_DATA = "Failed to search in data",
  SEARCH_CROSS_DATASET = "Failed to search cross dataset",
  FETCH_CONVERSATION = "Failed to fetch conversation",
  FETCH_CONVERSATIONS = "Failed to fetch conversations",
  PERSIST_CONVERSATION = "Failed to persist conversation",
  PERSIST_CONVERSATION_DEEP = "Failed to persist conversation deep",
  FETCH_MESSAGES = "Failed to fetch messages",
  UPDATE_CONVERSATION = "Failed to update conversation",
  DELETE_CONVERSATION = "Failed to delete conversation",
  FETCH_FIELDS_OF_SCIENCE = "Failed to fetch fields of science",
  FETCH_LICENSES = "Failed to fetch licenses",
  FETCH_USER_SETTINGS = "Failed to fetch user settings",
  SAVE_USER_SETTINGS = "Failed to save user settings",
  FETCH_PRINCIPAL = "Failed to fetch principal",
  FETCH_CONTEXT_GRANTS = "Failed to fetch context grants",
  FETCH_DATASET_CONTEXT_GRANTS = "Failed to fetch dataset context grants",
  FETCH_COLLECTION_CONTEXT_GRANTS = "Failed to fetch collection context grants",
}
