export enum ApiErrorMessage {
  NO_AUTH_TOKEN = "No authentication token available",
  FETCH_DATASETS_FAILED = "Failed to fetch datasets",
  FETCH_COLLECTIONS_FAILED = "Failed to fetch collections",
  FETCH_USER_COLLECTIONS_FAILED = "Failed to fetch user collections",
  CREATE_COLLECTION_FAILED = "Failed to create collection",
  ADD_DATASET_TO_COLLECTION_FAILED = "Failed to add dataset to collection",
  REMOVE_DATASET_FROM_COLLECTION_FAILED = "Failed to remove dataset from collection",
  DELETE_COLLECTION_FAILED = "Failed to delete collection",
  SEARCH_IN_DATA_FAILED = "Failed to search in data",
  SEARCH_CROSS_DATASET_FAILED = "Failed to search cross dataset",
  FETCH_CONVERSATION_FAILED = "Failed to fetch conversation",
  FETCH_CONVERSATIONS_FAILED = "Failed to fetch conversations",
  PERSIST_CONVERSATION_FAILED = "Failed to persist conversation",
  PERSIST_CONVERSATION_DEEP_FAILED = "Failed to persist conversation deep",
  FETCH_MESSAGES_FAILED = "Failed to fetch messages",
  UPDATE_CONVERSATION_FAILED = "Failed to update conversation",
  DELETE_CONVERSATION_FAILED = "Failed to delete conversation",
  FETCH_FIELDS_OF_SCIENCE_FAILED = "Failed to fetch fields of science",
  FETCH_LICENSES_FAILED = "Failed to fetch licenses",
  FETCH_USER_SETTINGS_FAILED = "Failed to fetch user settings",
  SAVE_USER_SETTINGS_FAILED = "Failed to save user settings",
}
