#!/bin/sh
set -e

echo "env.sh: Generating runtime environment..."

ENVSH_PREFIXES="${ENVSH_PREFIXES:-PUBLIC_|NEXT_PUBLIC_}"
ENVSH_OUTPUT="${ENVSH_OUTPUT:-./public/__env.js}"

if [ -f "./env.defaults.sh" ]; then
  set -a
  . ./env.defaults.sh
  set +a
fi

if [ -n "${NODE_ENV:-}" ] && [ -f ".env.${NODE_ENV}" ]; then
  set -a
  . ".env.${NODE_ENV}"
  set +a
elif [ -f ".env.local" ]; then
  set -a
  . ".env.local"
  set +a
elif [ -f ".env" ]; then
  set -a
  . ".env"
  set +a
fi

mkdir -p "$(dirname "$ENVSH_OUTPUT")"

matched_envs=$(env | grep -E "^(${ENVSH_PREFIXES})" || true)

echo "// Auto-generated by env.sh at $(date -u +"%Y-%m-%dT%H:%M:%SZ")" > "$ENVSH_OUTPUT"
echo "window.__env = {" >> "$ENVSH_OUTPUT"

if [ -n "$matched_envs" ]; then
  printf '%s\n' "$matched_envs" |
    awk -F= '
      {
        raw=$1;
        val=substr($0, length($1)+2);
        pr=0;
        key=raw;

        if (raw ~ /^PUBLIC_/) { key=substr(raw, 8); pr=2 }
        else if (raw ~ /^NEXT_PUBLIC_/) { key=substr(raw, 13); pr=1 }

        if (!(key in bestPr) || pr > bestPr[key]) {
          bestPr[key]=pr;
          bestVal[key]=val;
        }
        if (!(key in seen)) { seen[key]=1; order[++n]=key }
      }
      END {
        for (i=1; i<=n; i++) {
          k=order[i];
          printf "%s\t%s\n", k, bestVal[k]
        }
      }
    ' |
    while IFS=$(printf '\t') read -r key value; do
      escaped_value=$(printf '%s' "$value" | sed 's/\\/\\\\/g' | sed 's/"/\\"/g')
      echo "  \"$key\": \"$escaped_value\"," >> "$ENVSH_OUTPUT"
    done
fi

echo "};" >> "$ENVSH_OUTPUT"
echo "env.sh: Generated $ENVSH_OUTPUT"

exec "$@"
